/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_uas;

import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yosua Putra Pratama
 */
public class GUI extends javax.swing.JFrame {

    ArrayList<Kendaraan> nKendaraan;
    String header[] = new String[]{"Kode","Pemilik","Alamat","Mobil","Roda","Bahan Bakar","Bagian Check","Kerusakan","Kategori"};
    DefaultTableModel dtm;
    int row, col;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        nKendaraan = new ArrayList<>();
        dtm = new DefaultTableModel(header, 0);
        jTable1.setModel(dtm);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_mobil = new javax.swing.JTextField();
        txt_roda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_kerusakan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_bahanBakar = new javax.swing.JTextField();
        txt_bagianCheck = new javax.swing.JTextField();
        btn_input = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check Up");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        jLabel1.setText("Car General Check Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Pelanggan\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel2.setText("Pemilik");

        txt_nama.setBackground(new java.awt.Color(255, 255, 204));
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_alamat.setBackground(new java.awt.Color(255, 255, 204));
        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        jLabel3.setText("Alamat");

        jLabel5.setText("Roda");

        jLabel6.setText("Bahan Bakar");

        jLabel4.setText("Mobil");

        txt_mobil.setBackground(new java.awt.Color(255, 255, 204));

        txt_roda.setBackground(new java.awt.Color(255, 255, 204));

        jLabel7.setText("Bagian Check Up");

        txt_kerusakan.setBackground(new java.awt.Color(255, 255, 204));

        jLabel8.setText("Tingkat Kerusakan");

        jLabel10.setText("%");

        txt_bahanBakar.setBackground(new java.awt.Color(255, 255, 204));
        txt_bahanBakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bahanBakarActionPerformed(evt);
            }
        });

        txt_bagianCheck.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txt_nama)
                    .addComponent(txt_mobil)
                    .addComponent(txt_roda)
                    .addComponent(txt_bahanBakar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_bagianCheck))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_roda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_bahanBakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_bagianCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 430, 360));

        btn_input.setBackground(new java.awt.Color(204, 204, 255));
        btn_input.setText("Input");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        jPanel1.add(btn_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Pemilik", "Alamat", "Mobil", "Roda", "Bahan Bakar", "Bagian Check", "Kerusakan", "Kategori"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 990, 110));

        jLabel9.setText("No.Antrian");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txt_kode.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(txt_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 50, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete.setBackground(new java.awt.Color(204, 204, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btn_keluar.setBackground(new java.awt.Color(204, 204, 255));
        btn_keluar.setText("Exit");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 400, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Anda Yakin Keluar?","Keluar",JOptionPane.OK_OPTION);
        if(answer==JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        int kode = Integer.parseInt(txt_kode.getText());
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        String mobil = txt_mobil.getText();
        int roda = Integer.parseInt(txt_roda.getText());
        String jbakar = txt_bahanBakar.getText();
        String part = txt_bagianCheck.getText();
        int kerusakan = Integer.parseInt(txt_kerusakan.getText());
        
        nKendaraan.add(new Kendaraan(kode, nama, alamat, mobil, roda, jbakar, part, kerusakan));
        
        dtm.setRowCount(0);
        for (int i = 0; i < nKendaraan.size(); i++){
            Object[] objs = {nKendaraan.get(i).kode, nKendaraan.get(i).nama, nKendaraan.get(i).alamat, nKendaraan.get(i).mobil, nKendaraan.get(i).roda, nKendaraan.get(i).jbakar, nKendaraan.get(i).part, nKendaraan.get(i).kerusakan, nKendaraan.get(i).kategori(kerusakan)};
            dtm.addRow(objs);
        }
        
        txt_kode.setText("");
        txt_nama.setText("");
        txt_alamat.setText("");
        txt_mobil.setText("");
        txt_roda.setText("");
        txt_bahanBakar.setText("");
        txt_bagianCheck.setText("");
        txt_kerusakan.setText("");
    }//GEN-LAST:event_btn_inputActionPerformed

    private void txt_bahanBakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bahanBakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bahanBakarActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini?", "Delete", dialogButton);
        if(dialogResult == 0) {
            dtm.removeRow(row);
            nKendaraan.remove(row);
            dtm.setRowCount(1);
            for (int i = 0; i < nKendaraan.size(); i++){
                Object[] objs = {nKendaraan.get(i).kode, nKendaraan.get(i).nama, nKendaraan.get(i).alamat, nKendaraan.get(i).mobil, nKendaraan.get(i).roda, nKendaraan.get(i).jbakar, nKendaraan.get(i).part, nKendaraan.get(i).kerusakan, nKendaraan.get(i).kategori(nKendaraan.get(i).kerusakan)};
                dtm.addRow(objs);
            }
        } else {
        
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow () ==-1){
            if(jTable1.getRowCount() ==0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data Konsumen di dalam tabel");
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data Konsumen yang akan diubah");
            }
        }else{
            model.setValueAt(txt_kode.getText(), jTable1.getSelectedRow(), 0);
            model.setValueAt(txt_nama.getText(), jTable1.getSelectedRow(), 1);
            model.setValueAt(txt_alamat.getText(), jTable1.getSelectedRow(), 2);
            model.setValueAt(txt_mobil.getText(), jTable1.getSelectedRow(), 3);
            model.setValueAt(txt_roda.getText(), jTable1.getSelectedRow(), 4);
            model.setValueAt(txt_bahanBakar.getText(), jTable1.getSelectedRow(), 5);
            model.setValueAt(txt_bagianCheck.getText(), jTable1.getSelectedRow(), 6);
            model.setValueAt(txt_kerusakan.getText(), jTable1.getSelectedRow(), 7);           
            JOptionPane.showMessageDialog(null, "Data Konsumen Berhasil di Update");
        }
        reset();
        txt_kode.setText("");
        txt_nama.setText("");
        txt_alamat.setText("");
        txt_mobil.setText("");
        txt_roda.setText("");
        txt_bahanBakar.setText("");
        txt_bagianCheck.setText("");
        txt_kerusakan.setText("");
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_bagianCheck;
    private javax.swing.JTextField txt_bahanBakar;
    private javax.swing.JTextField txt_kerusakan;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_mobil;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_roda;
    // End of variables declaration//GEN-END:variables
}
