/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_uas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elkus Studio
 */
public class Form_checkup extends javax.swing.JFrame {

    /**
     * Creates new form Form_checkup
     */
    public Form_checkup() {
        initComponents();
    }
    
    public void reset(){
        txtNama.setText("");
        txtMerkMobil.setText("");
        txtNamaMobil.setText("");
        rbBanTidakRetak.setSelected(false);
        rbBanRetak.setSelected(false);
        rbKarbuBersih.setSelected(false);
        rbKarbuKotor.setSelected(false);
        rbLampuMati.setSelected(false);
        rbLampuNyala.setSelected(false);
        rbLengkap.setSelected(false);
        rbTidakLengkap.setSelected(false);
        rbOliBening.setSelected(false);
        rbOliHitam.setSelected(false);
        rbRadiatorKosong.setSelected(false);
        rbRadiatorPenuh.setSelected(false);
        rbRemBerfungsiBaik.setSelected(false);
        rbRemBerfungsiKurang.setSelected(false);
        rbWiperNormal.setSelected(false);
        rbWiperTidakBerfungsi.setSelected(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNamaMobil = new javax.swing.JTextField();
        txtMerkMobil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rbKarbuBersih = new javax.swing.JRadioButton();
        rbKarbuKotor = new javax.swing.JRadioButton();
        rbRadiatorPenuh = new javax.swing.JRadioButton();
        rbRadiatorKosong = new javax.swing.JRadioButton();
        rbOliBening = new javax.swing.JRadioButton();
        rbOliHitam = new javax.swing.JRadioButton();
        rbRemBerfungsiBaik = new javax.swing.JRadioButton();
        rbRemBerfungsiKurang = new javax.swing.JRadioButton();
        rbBanTidakRetak = new javax.swing.JRadioButton();
        rbBanRetak = new javax.swing.JRadioButton();
        rbLampuNyala = new javax.swing.JRadioButton();
        rbLampuMati = new javax.swing.JRadioButton();
        rbWiperNormal = new javax.swing.JRadioButton();
        rbWiperTidakBerfungsi = new javax.swing.JRadioButton();
        rbLengkap = new javax.swing.JRadioButton();
        rbTidakLengkap = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_data = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SISTEM GENERAL CHECK UP MOBIL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Mobil");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Merk Mobil");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Checking Up");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Karburator");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Air Radiator");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Oli Mesin");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rem dan Kaki-kaki");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Ban");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Lampu-lampu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Wiper");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Kelengkapan Mobil (STNK,SIM,P3K)");

        rbKarbuBersih.setBackground(new java.awt.Color(255, 204, 153));
        rbKarbuBersih.setText("Bersih");

        rbKarbuKotor.setBackground(new java.awt.Color(255, 204, 153));
        rbKarbuKotor.setText("Kotor");

        rbRadiatorPenuh.setBackground(new java.awt.Color(255, 204, 153));
        rbRadiatorPenuh.setText("Penuh");

        rbRadiatorKosong.setBackground(new java.awt.Color(255, 204, 153));
        rbRadiatorKosong.setText("Kosong");

        rbOliBening.setBackground(new java.awt.Color(255, 204, 153));
        rbOliBening.setText("Bening");

        rbOliHitam.setBackground(new java.awt.Color(255, 204, 153));
        rbOliHitam.setText("Hitam Pekat");

        rbRemBerfungsiBaik.setBackground(new java.awt.Color(255, 204, 153));
        rbRemBerfungsiBaik.setText("Berfungsi Baik");

        rbRemBerfungsiKurang.setBackground(new java.awt.Color(255, 204, 153));
        rbRemBerfungsiKurang.setText("Berfungsi Kurang Baik");

        rbBanTidakRetak.setBackground(new java.awt.Color(255, 204, 153));
        rbBanTidakRetak.setText("Tidak Ada Retakan");

        rbBanRetak.setBackground(new java.awt.Color(255, 204, 153));
        rbBanRetak.setText("Ada Retakan");

        rbLampuNyala.setBackground(new java.awt.Color(255, 204, 153));
        rbLampuNyala.setText("Menyala");

        rbLampuMati.setBackground(new java.awt.Color(255, 204, 153));
        rbLampuMati.setText("Tidak Menyala");

        rbWiperNormal.setBackground(new java.awt.Color(255, 204, 153));
        rbWiperNormal.setText("Berfungsi Normal");

        rbWiperTidakBerfungsi.setBackground(new java.awt.Color(255, 204, 153));
        rbWiperTidakBerfungsi.setText("Tidak Berfungsi");

        rbLengkap.setBackground(new java.awt.Color(255, 204, 153));
        rbLengkap.setText("Lengkap");

        rbTidakLengkap.setBackground(new java.awt.Color(255, 204, 153));
        rbTidakLengkap.setText("Tidak Lengkap");

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setText("TAMPILKAN DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tb_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Nama Mobil", "Merk Mobil", "Karburator", "Air Radiator", "Oli Mesin", "Rem dan Kaki-kaki", "Ban", "Lampu-lampu", "Wiper", "Kelengkapan Mobil", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tb_data);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("HAPUS DATA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(361, 361, 361))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(468, 468, 468)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNama)
                                            .addComponent(txtNamaMobil)
                                            .addComponent(txtMerkMobil, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbKarbuBersih)
                                            .addComponent(rbRadiatorPenuh)
                                            .addComponent(rbOliBening)
                                            .addComponent(rbRemBerfungsiBaik)
                                            .addComponent(rbBanTidakRetak)
                                            .addComponent(rbLampuNyala)
                                            .addComponent(rbWiperNormal)
                                            .addComponent(rbLengkap))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbOliHitam)
                                            .addComponent(rbRadiatorKosong)
                                            .addComponent(rbKarbuKotor)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(rbRemBerfungsiKurang))
                                            .addComponent(rbBanRetak)
                                            .addComponent(rbLampuMati)
                                            .addComponent(rbWiperTidakBerfungsi)
                                            .addComponent(rbTidakLengkap))))))
                        .addGap(0, 449, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMerkMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel6)
                                                            .addComponent(rbKarbuBersih))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel7))
                                                    .addComponent(rbRadiatorPenuh))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel8)
                                                    .addComponent(rbOliBening))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9))
                                            .addComponent(rbRemBerfungsiBaik)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(rbKarbuKotor)
                                                        .addGap(35, 35, 35))
                                                    .addComponent(rbRadiatorKosong))
                                                .addGap(18, 18, 18)
                                                .addComponent(rbOliHitam)
                                                .addGap(35, 35, 35))
                                            .addComponent(rbRemBerfungsiKurang))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbBanTidakRetak)
                                        .addComponent(rbBanRetak)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbLampuNyala)
                                .addComponent(rbLampuMati)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbWiperNormal)
                        .addComponent(rbWiperTidakBerfungsi)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rbLengkap)
                    .addComponent(rbTidakLengkap))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int karburator = 0,radiator = 0,oli=0,rem=0,ban=0,lampu=0,wiper=0,kelengkapan=0;
        String ket = "";
        DefaultTableModel model = (DefaultTableModel) tb_data.getModel();
        if(txtNama.getText().trim().equals("") || txtNamaMobil.getText().trim().equals("") || txtMerkMobil.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Data yang anda masukkan belum lengkap, Silahkan Diisi Ulang!");
        }else{
            if(rbKarbuBersih.isSelected()){
               karburator = 100;
            }else if(rbKarbuKotor.isSelected()){
                karburator = 10;
            }else{
                JOptionPane.showMessageDialog(null, "Karburator Hanya Boleh Pilih Salah Satu ");
            }
            
            if(rbRadiatorPenuh.isSelected()){
                radiator = 100;
            }else if(rbRadiatorKosong.isSelected()){
                radiator = 0;
            }else{
                JOptionPane.showMessageDialog(null, "Air Radiator Hanya Boleh Pilih Salah Satu ");
            }
            
            if(rbOliBening.isSelected()){
                oli = 100;
            }else if(rbOliHitam.isSelected()){
                oli = 10;
            }else{
                JOptionPane.showMessageDialog(null, "Oli Mesin Hanya Boleh Pilih Salah Satu ");
            }
            
            if(rbRemBerfungsiBaik.isSelected()){
                rem = 100;
            }else if(rbRemBerfungsiKurang.isSelected()){
                rem = 0;
            }else{
                JOptionPane.showMessageDialog(null, "Rem dan Kaki-kaki Hanya Boleh Pilih Salah Satu ");
            }
            
            if(rbBanTidakRetak.isSelected()){
                ban = 100;
            }else if(rbBanRetak.isSelected()){
                ban = 10;
            }else{
                JOptionPane.showMessageDialog(null, "Ban Hanya Boleh Pilih Salah Satu ");
            }
            
            if(rbLampuNyala.isSelected()){
                lampu = 100;
            }else if(rbLampuMati.isSelected()){
                lampu = 0;
            }else{
                JOptionPane.showMessageDialog(null, "Lampu-lampu Hanya Boleh Pilih Salah Satu ");
            }
            
            if(rbWiperNormal.isSelected()){
                wiper = 100;
            }else if(rbWiperTidakBerfungsi.isSelected()){
                wiper = 10;
            }else{
                JOptionPane.showMessageDialog(null, "Wiper Hanya Boleh Pilih Salah Satu ");
            }
            
            if(rbLengkap.isSelected()){
                kelengkapan = 100;
            }else if(rbTidakLengkap.isSelected()){
                kelengkapan = 0;
            }else{
                JOptionPane.showMessageDialog(null, "Kelangkapan Mobil Hanya Boleh Pilih Salah Satu ");
            }
            
            int hasil = karburator + radiator + oli + rem + lampu + wiper + ban + kelengkapan;
            if(hasil >= 600){
                ket = "Layak Jalan";
            }else if(hasil < 549){
                ket = "Tidak Layak Jalan";
            }
            model.addRow(new Object[]{txtNama.getText(),txtNamaMobil.getText(),txtMerkMobil.getText(),karburator,radiator,oli,rem,ban,lampu,wiper,kelengkapan,ket});
            JOptionPane.showMessageDialog(null, "Anda Berhasil Menginputkan Data");
            reset();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tb_data.getModel();
        if(tb_data.getSelectedRow()==-1){
            if(tb_data.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam tabel");
            }else{
                JOptionPane.showMessageDialog(null, "Silahkan Pilih Data Yang Akan dihapus Terlebih Dahulu!");
            }
        }else{
            model.removeRow(tb_data.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_checkup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_checkup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_checkup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_checkup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_checkup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbBanRetak;
    private javax.swing.JRadioButton rbBanTidakRetak;
    private javax.swing.JRadioButton rbKarbuBersih;
    private javax.swing.JRadioButton rbKarbuKotor;
    private javax.swing.JRadioButton rbLampuMati;
    private javax.swing.JRadioButton rbLampuNyala;
    private javax.swing.JRadioButton rbLengkap;
    private javax.swing.JRadioButton rbOliBening;
    private javax.swing.JRadioButton rbOliHitam;
    private javax.swing.JRadioButton rbRadiatorKosong;
    private javax.swing.JRadioButton rbRadiatorPenuh;
    private javax.swing.JRadioButton rbRemBerfungsiBaik;
    private javax.swing.JRadioButton rbRemBerfungsiKurang;
    private javax.swing.JRadioButton rbTidakLengkap;
    private javax.swing.JRadioButton rbWiperNormal;
    private javax.swing.JRadioButton rbWiperTidakBerfungsi;
    private javax.swing.JTable tb_data;
    private javax.swing.JTextField txtMerkMobil;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaMobil;
    // End of variables declaration//GEN-END:variables
}
